### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by AlexanderSiguenza** [mariobeltran99/investigacion2DSM#5]
Realizaron un buen trabajo en el documento CREATIVO E INFORMACION CONSISA. El mejor capitulo fue el 4, le sigue el 2 y el 3 quedo bien pero se podía hacer mejor. bien implementado el patrón MVP.

**Comment by mariobeltran99** [comment]
Necesitaba el 10 para pasarla con 10 la materia 💯

**Comment by AlexanderSiguenza** [comment]
El capitulo 3 quien lo hiso ?

**Comment by mariobeltran99** [comment]
No sé quién lo hizo
